### PR TITLE
Switch to test DB when testing

### PR DESCRIPTION
**Pull request by gregorylegarec**
Avoid resetting your contact database when running test.
This command could be enhanced by deleting the created database right after the
tests.

In an ideal world, the whole process of testing API calls should be done in a dedicated virtual environnment.

### CODE REVIEW

**Comment by m4dz** [comment]
I suggest you use `pretest:server` and `posttest:server` command hooks for switching DB instead of putting it in the command itself. What's your though about this?

**Comment by nono** [comment]
@gregorylegarec what is the status of this PR?

**Comment by gregorylegarec** [comment]
@nono I push changes but I amended my commit : that was a great idea for PR readbility.
So if it's ok for @m4dz we should merge.

**Comment by m4dz** [comment]
Thanks!

**Pull request merged**
