### PR TITLE
Fix select contact in Firefox mobile - fix #26 .

### LINKED ISSUE #26: Clicking a contact doesn't open it (Android / Firefox)
Confirmed on Android 4.3 and 4.4

### PR DESCRIPTION
**Pull request by jacquarg**
Update jquery.nicescroll to 3.6.0 . 

Needs build.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you

**Comment by frankrousseau** [comment]
I commited the build. It works on my phone too. Thank you for the fix!

**Comment by jacquarg** [comment]
Cool ! Thanks for the build. 
I am always hesitating about which is the right moment to build.

**Comment by frankrousseau** [comment]
That's good. It's easy to review your PR that way.

**Comment by frankrousseau** [comment]
Build in the PR are more for functional reviews. It's better to add it once the code review is done.

**Pull request merged**
