### PR TITLE
Remove FN field configuration

### PR DESCRIPTION
**Pull request by jacquarg**
Change politics about Contact.n and Contact.fn fields : both MUST be present in datasystem, and are present in cozy-contacts app. And name displaying format in app doesn't rely on fn field anymore (no migration anymore).

To do that :
* some tweaks in server/models/contact, remove dependency against Config doctype in server.
* config document is only used in client, to create the displayName field, used in contact list.
* some tweaks on vcard parsing (quoted-printable, strange line folding convention, ...).

### CODE REVIEW

**Comment by jsilvestre** [comment]
There is still issue with "weird" name because you extract "n" from "fn". See with " Pierre Kevin De la Huchette". This is ok to try to guess for badly formed vCard, but Contacts should be things properly. Or am I missing something?

**Comment by jacquarg** [comment]
Yes, no easy way for "Pierre Kevin De la Huchette". Google has some tricks to improve it's 'fn' to 'n' algorithme (recognise Sir, Dr as prefix, "de la" as name particle ...) but nothing determinist.

We can distinguish two cases :
1. It's an import, where 'N' wasn't filed. To comply with vCard 3 , N and FN MUST be filed (vCard 4, only FN is mandatory ... ), so automatic N and FN filling seems as the less bad way.
2. It's a new contact, manually inserted in cozy-contact. The modal 'edit name' allows to fill up each subfield (first name, middle name, suffix, ....) individually, unambiguously. As proposed earlier, we could force unambiguous field, or at least highlight "edit name" button when ambiguousity appens. Any way, when FN and N are setted, they aren't modified automatically anymore.

**Comment by aenario** [comment]
For automatic filling of N, I'd reccommend putting everything in first name, the user can change it from the "edit name" if (and only if) it is a problem with her other clients.

**Comment by jsilvestre** [comment]
What you suggest would prevent sort by last name, right?

**Comment by aenario** [comment]
No, if the user sort by lastname, its contact will already be written as lastname firstname

**Comment by jacquarg** [comment]
Last name will not be completly broken, but it will look like it, but badly cutted complex names looks broken yet ( "Huchette, Pierre" ). But they will appears as ", de la Huchette Pierre" ... (all starts with ",")
For the 1. case (import), your recomendation "all in first name" looks safer.
But it will be sad to do that in second case, or we should do something in the UX to overpass that.

**Comment by aenario** [comment]
Ok, let's be scientific about this : 

We have the following cases : 
A - Imported contact with FN and no N
B - Imported contact with N and no FN
C - Imported contact with both
D - Mannualy entered contact with FN and no N
E - Mannualy entered contact with both

And the following conventions : 
1 - firstname lastname
2 - lastname firstname

My proposal is to 
- sort by FN
- in case A, put FN as N's first name
- in case B1, set FN from N's first name + N's last name
- in case B2, set FN from N's last name + N's first name
- in case C & E, do nothing (assume FN follow user's convention)
- in case D1, put FN as N's first name
- in case D2, put FN as N's last name

**Comment by aenario** [comment]
PS : I am assuming we forget convention 3 (american) and remove the "," in convention 2

**Comment by jsilvestre** [comment]
Looks good to me, it solves the 95%.

**Comment by jacquarg** [comment]
Thanks for the presentation, we have the tools to talk now : ) !

vCard isn't clear about that, but gmail and android clients seems to leave FN field in a canonical form (Prefix Given Name Middle Names Last Name suffix), whatever the user choose to sort it's contacts list.
It make the FN field mainly useless, but we have to xomply with others client conventions to ensure interoperability.
If you have an example of client which rely on FN to display names, I change my story : ) .

That why my proposal is to :
* Sort by "displayName" on fly generated in client, based on _last name_ and _first name_ of N field.
* In case A, put FN as N's first name,
* In case B set FN from N's  first name + N's last name
* in case C & E, do nothing (assume FN follow user's convention)
* case D : push the user to fill lastname and firstname correctly.

That's why my

**Comment by aenario** [comment]
Ok, got it, I was assuming the other clients were using FN as a display name. For my defense, I haven't worked on vFormats for a while and forgot the logical thing never works... 

For the user to fill both first name & last name, we need to have them in the main form, otherwise it will be a PITA to open the modal everytime we want to add a new contact we can keep the modal for suffix, middle, prefix (or not, probably not)

If we go down that road, it might be simpler to just drop the FN field completely for cozy's model, we can generate it on the fly at export time from N and user's convention. This will avoid the problem of "what happen when the user edit the firstname -> do we change the FN ?"

pinging @frankrousseau , for this imply change to UX.

**Comment by jacquarg** [comment]
Yes, always a pleasure vFormats, the worst is that they are successful ^^.

I agree about UX :
we could do as on some old android phones a field first name and a field last name, and a '+' button to deploy the other ones ?

About FN field, I would have liked to agree, but I am scared about strange client, strange language, and vCard4 where FN (one or more !) is mandatory, but N optional. 
And indeed I found an example of FN not in firstname lastname order  (but I don't want to change my story) :

BEGIN:VCARD
VERSION:3.0
FN:東海林 一郎
N:東海林;一郎;;;
X-PHONETIC-FIRST-NAME:Ichirō
X-PHONETIC-LAST-NAME:Shōji
END:VCARD

from an interesting issue : https://github.com/owncloud/contacts/issues/119

I think it's premature to try to handle perfectly those exotics use cases (a bunch of them here : http://www.w3.org/International/questions/qa-personal-names.fr.php ), but be compatible with them, may be feasible and cool.

So I suggest to keep FN  and N field and touch them as less as we can (in sync use cases), even if it means data duplication in 80% of the use cases.

**Comment by jsilvestre** [comment]
I like it!

**Comment by jsilvestre** [comment]
Can you change `input#name` width so it fits the content rather than having an empty space?

In expanded mode, the input are tight to each other, can you add margin?

**Comment by jsilvestre** [comment]
Thank you! Please rebuild your latest commit, then I'll merge!

**Pull request merged**
