### PR TITLE
Switch to cozydb

### PR DESCRIPTION
**Pull request by aenario**

### CODE REVIEW

**Comment by frankrousseau** [comment]
It looks like you removed the History log. Did you remove the history tab from the contact view?

**Comment by aenario** [comment]
I only removed the Fing related history (PhoneCommunicationLog). We still have the ContactLog model & controller, which handles manual import of csv call logs. 

It should be extended to include emails, but we can hide it in the meantime.

**Comment by frankrousseau** [comment]
Let's remove it, noone uses it and we are looking for simplification.

**Comment by aenario** [comment]
Done, I also removed the widget.

**Comment by frankrousseau** [comment]
Is it good to merge?

**Comment by aenario** [comment]
Nope, still testing it

**Comment by aenario** [comment]
Ok, this should be good now !

**Comment by jsilvestre** [comment]
Sorry Romain, can you please rebase it against the latest upstream version?

**Comment by aenario** [comment]
Was rebased, waiting for Travis. 
Need functionnal testing.

@jacquarg I now jugglingdb can be weird, but https://github.com/cozy/cozy-contacts/blob/1fc1fbfff39fb5ddc1054de8e5bbdec875f8cc45/server/models/contact.coffee#L98 ?

**Comment by jacquarg** [comment]
Yes, it looks strange.
I just wanted to save the document if a migration occurs, and save method should be avoided, and changes was already applied, and it works.
If you have a cleaner solution it's all yours : )

**Comment by frankrousseau** [comment]
On my side, it works well. Except that, on the web UI, contact from my mobile doesn't display names until I click on the name field.

@clochix what do you think of the cozydb module? Do you think it's ready for the Contact application?

**Comment by jacquarg** [comment]
I think that this new bug come from _Contact.afterInitialize_ : https://github.com/cozy/cozy-contacts/blob/1fc1fbfff39fb5ddc1054de8e5bbdec875f8cc45/server/models/contact.coffee#L27-L41
isn't called anymore. So old contact document without 'n' fields aren't fixed.

_afterInitialize_ was a hook automatically called by jugglingdb after instantiations of models. I use it here to cleanup objects which come from the database. 
Cozydb could reproduce the afterInitialize api or something similar, or we could remove this onload check and replace it by a migration here. 
But I think that a way to easily transcript data just out of the database will be usefull in the future, as each app use the database, and has its own way use (or write) doctypes.

**Comment by aenario** [comment]
Thanks @jacquarg for the debug, 

cozydb.Model have the "cast" method which can be use for this usage. 
I will document it further and fix this.

This PR is in standby in the meantime

**Comment by aenario** [comment]
Ok, this should work now.

**Comment by frankrousseau** [comment]
Ok let's merge it!

**Comment by frankrousseau** [comment]
Congrats @aenario. That was a huge work.

**Comment by frankrousseau** [comment]
(But secretly I hate you because now I can update Cozy Light apps anymore ;)).

**Comment by aenario** [comment]
Dont worry, you wont need to 
https://github.com/aenario/cozydb/blob/master/src/pouchmodel.coffee ;-)

Simply pass the db option to americano.start. 
/!\ Need testing !

**Comment by frankrousseau** [comment]
+ need comments

That's awesome. Thank you

**Pull request merged**
