### PR TITLE
Up cozy-vcard version to 0.2.16 (client side)

### PR DESCRIPTION
**Pull request by frankrousseau**
Some errors were reported during contact export (#119). This new version of Cozy Vcard should fix
it.

### CODE REVIEW

**Comment by nono** [comment]
@frankrousseau I'm a bit lost. I don't find where this file is imported/used. And maybe we should use the same version for server-side.

**Comment by frankrousseau** [comment]
It's due to our poor system of vendor import, we include libs directly in a vendor folder (for the client side). Brunch doesn't handle NPM dependencies.

**Comment by nono** [comment]
But this lib should be imported with a `<script>`, `require`, `import` somewhere, no?

**Comment by frankrousseau** [comment]
No, Brunch packages everything and puts it before the app code. So every imported lib are available at the global level.

**Comment by m4dz** [comment]
Cool! Thanks @frankrousseau!

**Pull request merged**
