### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by frankrousseau**
Here are the improvements coming with that PR:

* I improved the UX of the name editor: 
     * add a boutton to leave the editor
     * better positioning of the buttons
* I improved responsiveness
     * cleaner layout (margin were missing)
     * do not focus by default on mobile (focus makes the keyboard pop, which is very annoying)

### CODE REVIEW

**Comment by aenario** [comment]
code looks good.
Could you build it so I can test ?

**Comment by frankrousseau** [comment]
@aenario done.

**Comment by aenario** [comment]
Works on my cozy.
I really dislike this double field even if know why its mandatory :'-(

**Comment by frankrousseau** [comment]
Yep, me too. That's why I improved a little bit the experience.

**Pull request merged**
