### PR TITLE
Fix/call order

### PR DESCRIPTION
**Pull request by Crash--**
- Add permissions needed for the cozy-bar
- Fix scheduler version in order to work well with hooks
- Fix call order to setStore to cozy-client

### CODE REVIEW

**Comment by Crash--** [comment]
> So to fix the call order, we need to move the initCozyBar call and wrap it in a set timeout? It's… really strange?

I really don't know why I've to wrap in a setTimeout((),0). I'll try without HMR to see if it comes from there, but yeah the real solution is to call initCozyBar after our setStore()

**Comment by y-lohse** [comment]
Ok well, the rest LGTM. If we can remove the setTimeout then great, otherwise we'll have to live with it I suppose :)

**Comment by ptbrowne** [comment]
Could you add a test checking that the initiliasation works correctly ? It would prevent a zealous refactorer from removing it.

**Comment by nono** [comment]
Can we merge this PR?

**Pull request merged**
