### PR TITLE
Ui: contact sheet improvements

### PR DESCRIPTION
**Pull request by m4dz**

### CODE REVIEW

**Comment by frankrousseau** [comment]
Could you rebase your commit? There is a missing debug

**Comment by m4dz** [comment]
I have rebased it on master before sending the PR and my branch seems up-to-date. Which debug is missing?

**Comment by frankrousseau** [comment]
Ok. I found the following problems:

* When you have a lot of fields, the left column style doesn't fill the whole height.
* When you add a tag the autocomplete combo is still displayed and in the wrong place (too much on the left).
* The more options buttons, lack of margins
* The name field width is too small
* The name widget is always fully extended. We should either remove the expand button or put back the non extended mode first.

I you need screenshot, let me know.

**Comment by m4dz** [comment]
Thanks for the feedback!

> - When you have a lot of fields, the left column style doesn't fill the whole height.
> - When you add a tag the autocomplete combo is still displayed and in the wrong place (too much on the left).

If you can provide me a screenshot, I take it, because I don't see what you mean.

> - The name widget is always fully extended.

I haven't the name widget fully extended (meaning with all fields visibles). Is it for new contacts or when you edit an existing one ?

**Comment by m4dz** [comment]
OK for me. I haven't fixed tags autocomplete box issue because it's too messy for this time. I'll add a Trello card to make a global component for this.

**Comment by frankrousseau** [comment]
Ok

**Comment by frankrousseau** [comment]
Thank you! The change are really nice and the UX is a lot better now.

**Pull request merged**
